spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mallsystem0?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: hb135119
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mallsystem1?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: hb135119
    sharding:
      tables:
        customer_inf:
          actual-data-nodes: ds${0..1}.customer_inf${0..1}
          database-strategy:
            inline:
              sharding-column: customer_inf_id
              algorithm-expression: ds$->{customer_inf_id % 2}
          table-strategy:
            inline:
              sharding-column: customer_id
              algorithm-expression: customer_inf$->{customer_id % 2}
          key-generator:
            type: SNOWFLAKE
            column: customer_inf_id
    props:
      sql:
        show: true
      executor:
        size: 12